Issue 497: Add Windows Build in Travis (#512)
close #497

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -17,7 +17,9 @@ addons:
     update: true
 
 matrix:
+  # Windows builds are experimental in Travis, ignore job results in case of failure!
   allow_failures:
+    - os: windows
     - os: linux
       env: DYNAMIC_ANALYSIS=ON PENGUINV_UNIT_TEST_RUN_COUNT=10 CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Debug"
   include:
@@ -88,6 +90,19 @@ matrix:
     - os: osx
       env: QT_BASE=latest CMAKE_OPTIONS=""
       before_install: source script/travis/install_qt5.sh
+    - os: windows
+      name: Windows (VS2015 Win32)
+      env:
+        - TARGET="Visual Studio 14 2015"
+        - BUILD_TYPE="Release"
+      before_install: if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then choco install -y vcbuildtools --version 2015.4 --force; fi
+    - os: windows
+      name: Windows (VS2015 x64)
+      language: bash
+      env:
+        - TARGET="Visual Studio 14 2015 Win64"
+        - BUILD_TYPE="Release"
+      before_install: if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then choco install -y vcbuildtools --version 2015.4 --force; fi
 
 before_script:
   # Let CMake generate build files
@@ -99,19 +114,27 @@ before_script:
     fi
     if [[ "$STATIC_ANALYSIS" != "ON" ]]; then
       mkdir -p build && cd build
-      cmake .. ${CMAKE_OPTIONS}
+      if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
+        if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then
+          cmake -G "$TARGET" ..;
+        fi
+      else
+        cmake .. ${CMAKE_OPTIONS}
+      fi
     fi
 
 script:
   - |
     # Build and run tests
-    set -e
-    cmake --build .
-    set +e
-    if [[ "$DYNAMIC_ANALYSIS" == "ON" ]]; then
-      ctest --overwrite MemoryCheckCommandOptions="--show-reachable=no" \
-            -R unit_test --extra-verbose \
-            -T MemCheck # execute unit_test only
-    else
-      ctest -E 'perf_test' --extra-verbose # execute unit_test and unit_test_opencl
+    if [[ "$TRAVIS_EVENT_TYPE" == "cron" || "$TRAVIS_OS_NAME" != "windows" ]]; then
+      set -e
+      cmake --build . --config $BUILD_TYPE # --config is ignored on Linux/MacOS
+      set +e
+      if [[ "$DYNAMIC_ANALYSIS" == "ON" ]]; then
+        ctest --overwrite MemoryCheckCommandOptions="--show-reachable=no" \
+              -R unit_test --extra-verbose \
+              -T MemCheck # execute unit_test only
+      else
+        ctest -C $BUILD_TYPE -E 'perf_test' --extra-verbose # execute unit_test and unit_test_opencl
+      fi
     fi
